config/routes.rb
ClientWorkouts::Application.routes.draw do
  resources :client_workouts

end

app/models/client_workout.rb
class ClientWorkout < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/client_workouts_controller.rb
class ClientWorkoutsController < ApplicationController
  before_action :set_client_workout, only: [:show, :edit, :update, :destroy]

  # GET /client_workouts
  # GET /client_workouts.json
  def index
    @client_workouts = ClientWorkout.all
  end

  # GET /client_workouts/1
  # GET /client_workouts/1.json
  def show
  end

  # GET /client_workouts/new
  def new
    @client_workout = ClientWorkout.new
  end

  # GET /client_workouts/1/edit
  def edit
  end

  # POST /client_workouts
  # POST /client_workouts.json
  def create
    @client_workout = ClientWorkout.new(client_workout_params)

    respond_to do |format|
      if @client_workout.save
        format.html { redirect_to @client_workout, notice: 'Client workout was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client_workout }
      else
        format.html { render action: 'new' }
        format.json { render json: @client_workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client_workouts/1
  # PATCH/PUT /client_workouts/1.json
  def update
    respond_to do |format|
      if @client_workout.update(client_workout_params)
        format.html { redirect_to @client_workout, notice: 'Client workout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client_workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_workouts/1
  # DELETE /client_workouts/1.json
  def destroy
    @client_workout.destroy
    respond_to do |format|
      format.html { redirect_to client_workouts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client_workout
      @client_workout = ClientWorkout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_workout_params
      params.require(:client_workout).permit(:client_name, :trainer, :duration_mins, :date_of_workout, :paid_amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_workouts_helper.rb
module ClientWorkoutsHelper
end

app/views/client_workouts/_form.html.erb
<%= form_for(@client_workout) do |f| %>
  <% if @client_workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client_workout.errors.count, "error") %> prohibited this client_workout from being saved:</h2>

      <ul>
      <% @client_workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_name %><br>
    <%= f.text_field :client_name %>
  </div>
  <div class="field">
    <%= f.label :trainer %><br>
    <%= f.text_field :trainer %>
  </div>
  <div class="field">
    <%= f.label :duration_mins %><br>
    <%= f.number_field :duration_mins %>
  </div>
  <div class="field">
    <%= f.label :date_of_workout %><br>
    <%= f.date_select :date_of_workout %>
  </div>
  <div class="field">
    <%= f.label :paid_amount %><br>
    <%= f.text_field :paid_amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/client_workouts/edit.html.erb
<h1>Editing client_workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @client_workout %> |
<%= link_to 'Back', client_workouts_path %>

app/views/client_workouts/index.html.erb
<h1>Listing client_workouts</h1>

<table>
  <thead>
    <tr>
      <th>Client name</th>
      <th>Trainer</th>
      <th>Duration mins</th>
      <th>Date of workout</th>
      <th>Paid amount</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @client_workouts.each do |client_workout| %>
      <tr>
        <td><%= client_workout.client_name %></td>
        <td><%= client_workout.trainer %></td>
        <td><%= client_workout.duration_mins %></td>
        <td><%= client_workout.date_of_workout %></td>
        <td><%= client_workout.paid_amount %></td>
        <td><%= link_to 'Show', client_workout %></td>
        <td><%= link_to 'Edit', edit_client_workout_path(client_workout) %></td>
        <td><%= link_to 'Destroy', client_workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client workout', new_client_workout_path %>

app/views/client_workouts/new.html.erb
<h1>New client_workout</h1>

<%= render 'form' %>

<%= link_to 'Back', client_workouts_path %>

app/views/client_workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client name:</strong>
  <%= @client_workout.client_name %>
</p>

<p>
  <strong>Trainer:</strong>
  <%= @client_workout.trainer %>
</p>

<p>
  <strong>Duration mins:</strong>
  <%= @client_workout.duration_mins %>
</p>

<p>
  <strong>Date of workout:</strong>
  <%= @client_workout.date_of_workout %>
</p>

<p>
  <strong>Paid amount:</strong>
  <%= @client_workout.paid_amount %>
</p>

<%= link_to 'Edit', edit_client_workout_path(@client_workout) %> |
<%= link_to 'Back', client_workouts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClientWorkouts</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/client_workouts.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>ClientWorkouts: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<span style="text-align: right">
  <%= form_tag "/client_workouts/find" do %>
    <%= text_field_tag :search_string %>
    <%= submit_tag "Search" %>
  <% end %>
</span>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield %>

</body>
</html>